"""
GPT-Image Client for generating images using OpenAI's GPT-Image model.

This client interfaces with OpenAI's Image Generation API to create
illustrations for story pages using the gpt-image-1 model.
"""

import httpx
import os
import asyncio
from typing import Optional

from src.ai.base_client import BaseImageClient
from src.models.config import OpenAIConfig


class GPTImageClient(BaseImageClient):
    """
    Client for OpenAI GPT-Image generation service.

    GPT-Image (model: gpt-image-1) is OpenAI's text-to-image generation model
    that creates high-quality illustrations from text prompts.
    """

    # OpenAI API endpoint
    API_BASE_URL = "https://api.openai.com/v1"

    def __init__(self, config: OpenAIConfig, model: str = "gpt-image-1"):
        """
        Initialize the GPT-Image client.

        Args:
            config: OpenAIConfig with API key and timeout
            model: Image model to use (default: "gpt-image-1")
        """
        self.config = config
        # Get API key from config or environment variable
        self.api_key = config.api_key or os.getenv('OPENAI_API_KEY', '')
        self.model = model
        self.timeout = config.timeout

    async def generate_image(self, prompt: str, **kwargs) -> str:
        """
        Generate an image using GPT-Image with automatic retry on server errors.

        Args:
            prompt: The text prompt for image generation
            **kwargs: Additional parameters:
                - size (str): Image size (e.g., "1024x1024", "1024x1792", "1792x1024")
                - quality (str): "standard" or "hd"
                - style (str): "vivid" or "natural"
                - n (int): Number of images to generate (default: 1)

        Returns:
            URL to the generated image

        Raises:
            httpx.HTTPError: If the API request fails after retries
            ValueError: If API key is missing
        """
        if not self.api_key:
            raise ValueError(
                "OpenAI API key not found. Please set OPENAI_API_KEY in your .env file"
            )

        # Build request data
        request_data = {
            "model": self.model,
            "prompt": prompt,
            "n": kwargs.get('n', 1)  # Number of images
        }

        # Set size parameter (default to 1024x1024)
        request_data['size'] = kwargs.get('size', '1024x1024')

        # Add optional quality and style parameters
        if 'quality' in kwargs:
            request_data['quality'] = kwargs['quality']
        if 'style' in kwargs:
            request_data['style'] = kwargs['style']

        # Prepare headers with API key
        headers = {
            "Authorization": f"Bearer {self.api_key}",
            "Content-Type": "application/json"
        }

        # Retry logic for transient server errors
        max_retries = 3
        retry_delay = 2  # seconds

        for attempt in range(max_retries):
            try:
                # Make API request
                async with httpx.AsyncClient(timeout=self.timeout) as client:
                    response = await client.post(
                        f"{self.API_BASE_URL}/images/generations",
                        json=request_data,
                        headers=headers
                    )

                    # Check for errors
                    if response.status_code == 200:
                        # Success! Parse response
                        response_data = response.json()

                        # API returns an array of image objects
                        # Each has a 'url' field with the generated image URL
                        if 'data' not in response_data or len(response_data['data']) == 0:
                            raise ValueError("No image was generated by GPT-Image")

                        image_url = response_data['data'][0]['url']
                        return image_url

                    # Handle different error types
                    error_detail = response.text
                    try:
                        error_json = response.json()
                        if 'error' in error_json and 'message' in error_json['error']:
                            error_detail = error_json['error']['message']
                    except:
                        pass

                    # Retry on server errors (500-599)
                    if 500 <= response.status_code < 600:
                        if attempt < max_retries - 1:
                            print(f"GPT-Image server error (attempt {attempt + 1}/{max_retries}). Retrying in {retry_delay}s...")
                            await asyncio.sleep(retry_delay)
                            retry_delay *= 2  # Exponential backoff
                            continue
                        else:
                            raise httpx.HTTPError(
                                f"GPT-Image API error after {max_retries} attempts: {response.status_code} - {error_detail}"
                            )

                    # Don't retry on client errors (400-499) - these won't fix themselves
                    raise httpx.HTTPError(
                        f"GPT-Image API error: {response.status_code} - {error_detail}"
                    )

            except httpx.TimeoutException as e:
                if attempt < max_retries - 1:
                    print(f"GPT-Image timeout (attempt {attempt + 1}/{max_retries}). Retrying in {retry_delay}s...")
                    await asyncio.sleep(retry_delay)
                    retry_delay *= 2
                    continue
                else:
                    raise httpx.HTTPError(f"GPT-Image API timeout after {max_retries} attempts")

            except httpx.HTTPError:
                # Re-raise HTTP errors without retry (already handled above)
                raise

            except Exception as e:
                # Unexpected errors
                raise httpx.HTTPError(f"Unexpected error calling GPT-Image API: {str(e)}")
